/**
 * Prompt Template for AI Code Generation
 * 
 * This prompt instructs the LLM to generate optimized automation code
 * from recorded user actions.
 */

export type Framework = 'playwright' | 'cypress';
export type Language = 'typescript' | 'javascript';

export const CODE_GENERATION_PROMPT = {
  system: `You are an expert test automation engineer. Your task is to generate clean, maintainable, and robust automation code from recorded user actions.

Best practices to follow:
1. Use appropriate locator strategies (prefer data-testid, then ID, then semantic selectors)
2. Add proper waits and assertions
3. Handle dynamic content gracefully
4. Group related actions logically
5. Add descriptive comments for complex logic
6. Use Page Object Model patterns where applicable
7. Include error handling
8. Make the code reusable and maintainable

The generated code should be production-ready and follow industry best practices.`,

  userTemplate: (
    actionsJson: string,
    framework: Framework,
    language: Language,
    testName: string
  ): string => `
Generate ${framework.charAt(0).toUpperCase() + framework.slice(1)} automation code in ${language === 'typescript' ? 'TypeScript' : 'JavaScript'} for the following recorded actions:

## Test Name
${testName}

## Recorded Actions
\`\`\`json
${actionsJson}
\`\`\`

Generate the automation code following these requirements:
${framework === 'playwright' ? getPlaywrightRequirements() : getCypressRequirements()}

Return ONLY the code, no explanations. The code should be ready to run.`,
};

function getPlaywrightRequirements(): string {
  return `
- Use Playwright Test framework (@playwright/test)
- Use modern async/await patterns
- Use locator methods (page.locator, page.getByRole, page.getByTestId, etc.)
- Add appropriate assertions using expect()
- Include proper test structure with test.describe and test blocks
- Handle navigation with proper waits
- Use meaningful variable names`;
}

function getCypressRequirements(): string {
  return `
- Use Cypress testing framework
- Use cy.get(), cy.contains(), cy.find() for element selection
- Add appropriate assertions using .should()
- Include proper test structure with describe and it blocks
- Handle navigation with cy.visit() and proper waits
- Use meaningful variable names
- Chain commands appropriately`;
}

/**
 * Build file header based on framework and language
 */
export function buildCodeHeader(framework: Framework, language: Language, testName: string): string {
  const isTS = language === 'typescript';
  const date = new Date().toISOString();
  
  if (framework === 'playwright') {
    return `// Auto-generated by ThreeEyedRaven AI - ${date}
// Test: ${testName}
${isTS ? '' : '// @ts-check'}

${isTS ? "import { test, expect } from '@playwright/test';" : "const { test, expect } = require('@playwright/test');"}

`;
  } else {
    return `// Auto-generated by ThreeEyedRaven AI - ${date}
// Test: ${testName}
${isTS ? '' : '// @ts-check'}

`;
  }
}

// ============================================
// Two-Pass Code Generation Prompts
// ============================================

export interface CodeBlockPlan {
  name: string;
  description: string;
}

export const CODE_PLAN_PROMPT = {
  system: `You are an expert test automation engineer. Your task is to analyze recorded user actions and plan the structure of the automation code. You are ONLY listing the test functions/blocks — do NOT write any code yet.

For each block, provide:
- name: the function or test block name
- description: one sentence describing what it tests

Output a JSON array.`,

  userTemplate: (
    actionsJson: string,
    framework: Framework,
    language: Language,
    testName: string
  ): string => `
Plan the structure of ${framework.charAt(0).toUpperCase() + framework.slice(1)} automation code in ${language === 'typescript' ? 'TypeScript' : 'JavaScript'} for these recorded actions:

## Test Name
${testName}

## Recorded Actions
\`\`\`json
${actionsJson}
\`\`\`

List ALL test functions/blocks that should be generated. Return ONLY a JSON array:
\`\`\`json
[
  { "name": "test function or block name", "description": "what it tests" }
]
\`\`\`

Only return the JSON array, no additional text.`,
};

export const CODE_DETAIL_PROMPT = {
  system: `You are an expert test automation engineer. You have already planned the test structure. Now implement specific test blocks.

The generated code should be production-ready and follow industry best practices.`,

  userTemplate: (
    actionsJson: string,
    framework: Framework,
    language: Language,
    testName: string,
    blockNames: string[]
  ): string => `
Generate ${framework.charAt(0).toUpperCase() + framework.slice(1)} automation code in ${language === 'typescript' ? 'TypeScript' : 'JavaScript'} for ONLY these specific test blocks:

${blockNames.map((name, i) => `${i + 1}. ${name}`).join('\n')}

## Test Name
${testName}

## Recorded Actions
\`\`\`json
${actionsJson}
\`\`\`

Requirements:
${framework === 'playwright' ? getPlaywrightRequirements() : getCypressRequirements()}

Return ONLY the code for the specified blocks, no explanations. The code should be ready to run.`,
};

/**
 * Validate and clean generated code
 */
export function validateGeneratedCode(code: string, framework: Framework): {
  valid: boolean;
  cleaned: string;
  issues: string[];
} {
  const issues: string[] = [];
  let cleaned = code;

  // Remove markdown code blocks if present
  cleaned = cleaned.replace(/```(?:typescript|javascript|ts|js)?\n?/g, '');
  cleaned = cleaned.replace(/```\n?/g, '');
  cleaned = cleaned.trim();

  // Check for required imports/structure
  if (framework === 'playwright') {
    if (!cleaned.includes('test') && !cleaned.includes('expect')) {
      issues.push('Missing Playwright test imports');
    }
    if (!cleaned.includes('page')) {
      issues.push('No page interactions found');
    }
  } else {
    if (!cleaned.includes('describe') && !cleaned.includes('it')) {
      issues.push('Missing Cypress test structure');
    }
    if (!cleaned.includes('cy.')) {
      issues.push('No Cypress commands found');
    }
  }

  return {
    valid: issues.length === 0,
    cleaned,
    issues,
  };
}
