/**
 * PlaywrightBuilder - Generates Playwright test code from test cases
 * 
 * Generates both:
 * - Individual test snippets for each test case
 * - Complete test files with all test cases grouped
 */

import { AnalyzedField } from './fieldAnalyzer';
import { TestCaseRule } from './ruleEngine';

// GeneratedTestCase type - matches testCaseGenerator.ts interface
// Some fields optional to support manual test cases
interface GeneratedTestCase {
  id: string;
  sessionId: string;
  fieldId?: string;
  fieldName?: string;
  fieldSelector?: string;
  category?: string;
  name: string;
  description?: string;
  testValue?: string;
  expectedResult: string;
  priority: string;
  status: string;
  notes?: string;
  playwrightCode?: string;
  source?: 'auto' | 'manual' | 'ai';
  steps?: string;
  createdAt: number;
  updatedAt: number;
}

export class PlaywrightBuilder {
  /**
   * Build a single test case code snippet
   */
  buildSingleTest(field: AnalyzedField, rule: TestCaseRule): string {
    const locator = this.buildLocator(field);
    const testValue = rule.getTestValue(field);
    
    const lines: string[] = [
      `// Test: ${rule.name}`,
      `// ${rule.description}`,
    ];

    // Different actions based on field type
    switch (field.fieldType) {
      case 'text':
      case 'email':
      case 'password':
      case 'tel':
      case 'url':
      case 'search':
      case 'textarea':
        lines.push(`await page.locator('${locator}').clear();`);
        if (testValue) {
          lines.push(`await page.locator('${locator}').fill('${this.escapeString(testValue)}');`);
        }
        break;
        
      case 'number':
        lines.push(`await page.locator('${locator}').clear();`);
        if (testValue) {
          lines.push(`await page.locator('${locator}').fill('${testValue}');`);
        }
        break;
        
      case 'select':
        if (testValue === '[FIRST_OPTION]') {
          lines.push(`const options = await page.locator('${locator}').locator('option').all();`);
          lines.push(`if (options.length > 1) {`);
          lines.push(`  await page.locator('${locator}').selectOption({ index: 1 });`);
          lines.push(`}`);
        } else if (testValue === '[LAST_OPTION]') {
          lines.push(`const options = await page.locator('${locator}').locator('option').all();`);
          lines.push(`if (options.length > 0) {`);
          lines.push(`  await page.locator('${locator}').selectOption({ index: options.length - 1 });`);
          lines.push(`}`);
        } else if (testValue === '') {
          lines.push(`// Try to submit without selecting an option`);
        } else {
          lines.push(`await page.locator('${locator}').selectOption('${this.escapeString(testValue)}');`);
        }
        break;
        
      case 'checkbox':
      case 'radio':
        lines.push(`await page.locator('${locator}').click();`);
        break;
        
      default:
        lines.push(`await page.locator('${locator}').fill('${this.escapeString(testValue)}');`);
    }

    // Add assertion placeholder
    lines.push('');
    lines.push(`// Expected: ${rule.getExpectedResult(field)}`);
    lines.push(`// TODO: Add appropriate assertion based on application behavior`);

    return lines.join('\n');
  }

  /**
   * Build a complete test file from test cases
   */
  buildTestFile(testCases: GeneratedTestCase[], sessionName: string): string {
    const safeName = this.toSafeName(sessionName);
    
    const lines: string[] = [
      '// Auto-generated by Dashing - Test Case Generator',
      `// Session: ${sessionName}`,
      `// Generated: ${new Date().toISOString()}`,
      '',
      "import { test, expect } from '@playwright/test';",
      '',
      `test.describe('${safeName} - Generated Tests', () => {`,
      '',
    ];

    // Group test cases by field (or 'Manual Tests' for manual test cases)
    const byField = new Map<string, GeneratedTestCase[]>();
    for (const tc of testCases) {
      const groupName = tc.fieldName || (tc.source === 'manual' ? 'Manual Tests' : 'Other Tests');
      const existing = byField.get(groupName) || [];
      existing.push(tc);
      byField.set(groupName, existing);
    }

    // Generate test describe block for each field
    for (const [fieldName, cases] of byField) {
      const safeFieldName = this.toSafeName(fieldName);
      
      lines.push(`  test.describe('${safeFieldName}', () => {`);
      
      for (const tc of cases) {
        lines.push('');
        lines.push(`    test('${tc.name}', async ({ page }) => {`);
        if (tc.description) {
          lines.push(`      // ${tc.description}`);
        }
        if (tc.category || tc.priority) {
          lines.push(`      // Category: ${tc.category || 'N/A'} | Priority: ${tc.priority}`);
        }
        lines.push('');
        
        // Add the actual test code
        if (tc.playwrightCode) {
          const codeLines = tc.playwrightCode.split('\n');
          for (const codeLine of codeLines) {
            lines.push(`      ${codeLine}`);
          }
        } else if (tc.fieldSelector) {
          lines.push(`      // Fill field with test value`);
          lines.push(`      await page.locator('${tc.fieldSelector}').clear();`);
          if (tc.testValue) {
            lines.push(`      await page.locator('${tc.fieldSelector}').fill('${this.escapeString(tc.testValue)}');`);
          }
          lines.push('');
          lines.push(`      // Expected: ${tc.expectedResult}`);
        } else {
          // Manual test case - add steps as comments
          if (tc.steps) {
            lines.push(`      // Steps:`);
            for (const step of tc.steps.split('\n')) {
              lines.push(`      // ${step}`);
            }
            lines.push('');
          }
          lines.push(`      // Expected: ${tc.expectedResult}`);
          lines.push(`      // TODO: Implement manual test automation`);
        }
        
        lines.push('    });');
      }
      
      lines.push('  });');
      lines.push('');
    }

    lines.push('});');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Build Playwright locator from field info
   * Uses the priority: XPath > data-testid > ID > CSS selector
   */
  private buildLocator(field: AnalyzedField): string {
    // 1. Use XPath if available
    if (field.xpath) {
      return field.xpath;
    }

    // 2. Check for data-testid in selector (already in selector format)
    if (field.selector.includes('[data-testid=')) {
      return field.selector;
    }

    // 3. Try to build from ID
    if (field.id.startsWith('id:')) {
      const id = field.id.substring(3);
      if (!/\d{5,}/.test(id)) { // Avoid auto-generated IDs
        return `#${id}`;
      }
    }

    // 4. Try to build from name attribute
    if (field.id.startsWith('name:')) {
      const name = field.id.substring(5);
      return `[name="${name}"]`;
    }

    // 5. Fall back to the recorded selector
    return field.selector;
  }

  /**
   * Escape string for JavaScript
   */
  private escapeString(str: string): string {
    return str
      .replace(/\\/g, '\\\\')
      .replace(/'/g, "\\'")
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/\t/g, '\\t');
  }

  /**
   * Convert name to safe identifier
   */
  private toSafeName(name: string): string {
    return name
      .replace(/[^a-zA-Z0-9\s-_]/g, '')
      .trim()
      .replace(/\s+/g, ' ');
  }
}

