/**
 * TemplateEngine - Generates code files from templates
 * 
 * Generates:
 * - Locator files (page.locators.ts)
 * - Page class files (page.ts)
 * - Test files (*.spec.ts)
 * - Config files (playwright.config.ts, package.json)
 */

import { RecordedAction } from '../../shared/types';
import { LocatorBuilder, LocatorResult } from './locatorBuilder';
import { DetectedPage } from './pageDetector';

export interface LocatorEntry {
  name: string;
  locator: LocatorResult;
  actionType: string;
}

export interface PageMethod {
  name: string;
  locatorName: string;
  actionType: string;
  comment: string;
  params?: { name: string; type: string }[];
  implementation: string;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

export class TemplateEngine {
  private locatorBuilder: LocatorBuilder;

  constructor() {
    this.locatorBuilder = new LocatorBuilder();
  }

  /**
   * Generate locators file for a page
   */
  generateLocatorsFile(page: DetectedPage): GeneratedFile {
    const locators = this.extractLocators(page);
    
    const content = `// Auto-generated by ThreeEyedRaven - Do not edit manually
// Page: ${page.title}
// URL: ${page.url}

export const ${page.className}Locators = {
${locators.map(l => `  // ${l.locator.comment}
  ${l.name}: "${this.escapeString(l.locator.locator)}",`).join('\n\n')}
} as const;

export type ${page.className}LocatorKeys = keyof typeof ${page.className}Locators;
`;

    return {
      path: `pages/${page.fileName}.locators.ts`,
      content,
    };
  }

  /**
   * Generate page class file
   */
  generatePageFile(page: DetectedPage): GeneratedFile {
    const locators = this.extractLocators(page);
    const methods = this.generateMethods(page, locators);
    
    const content = `// Auto-generated by ThreeEyedRaven
// Page: ${page.title}

import { Page, Locator } from '@playwright/test';
import { ${page.className}Locators } from './${page.fileName}.locators';

export class ${page.className} {
  readonly page: Page;

  constructor(page: Page) {
    this.page = page;
  }

  /**
   * Navigate to this page
   */
  async navigate(): Promise<void> {
    await this.page.goto('${this.escapeString(page.url)}');
  }

  /**
   * Get a locator by key
   */
  private getLocator(key: keyof typeof ${page.className}Locators): Locator {
    return this.page.locator(${page.className}Locators[key]);
  }

${methods.map(m => this.formatMethod(m)).join('\n\n')}
}
`;

    return {
      path: `pages/${page.fileName}.ts`,
      content,
    };
  }

  /**
   * Generate test file for all pages
   */
  generateTestFile(pages: DetectedPage[], testName: string): GeneratedFile {
    const imports = pages.map(p => 
      `import { ${p.className} } from '../pages/${p.fileName}';`
    ).join('\n');

    const testCases = this.generateTestCases(pages);
    
    const content = `// Auto-generated by ThreeEyedRaven
// Test: ${testName}

import { test, expect } from '@playwright/test';
${imports}

test.describe('${testName}', () => {
${testCases}
});
`;

    return {
      path: `tests/${this.toFileName(testName)}.spec.ts`,
      content,
    };
  }

  /**
   * Generate playwright.config.ts
   */
  generatePlaywrightConfig(baseUrl: string): GeneratedFile {
    const content = `// Auto-generated by ThreeEyedRaven
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  
  use: {
    baseURL: '${baseUrl}',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
`;

    return {
      path: 'playwright.config.ts',
      content,
    };
  }

  /**
   * Generate package.json
   */
  generatePackageJson(testName: string): GeneratedFile {
    const safeName = this.toFileName(testName);
    
    const content = `{
  "name": "${safeName}",
  "version": "1.0.0",
  "description": "Auto-generated Playwright tests by ThreeEyedRaven",
  "scripts": {
    "test": "playwright test",
    "test:headed": "playwright test --headed",
    "test:ui": "playwright test --ui",
    "report": "playwright show-report"
  },
  "devDependencies": {
    "@playwright/test": "^1.40.0",
    "@types/node": "^20.0.0",
    "typescript": "^5.0.0"
  }
}
`;

    return {
      path: 'package.json',
      content,
    };
  }

  /**
   * Generate tsconfig.json
   */
  generateTsConfig(): GeneratedFile {
    const content = `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "moduleResolution": "node",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "outDir": "./dist",
    "rootDir": "."
  },
  "include": ["**/*.ts"],
  "exclude": ["node_modules"]
}
`;

    return {
      path: 'tsconfig.json',
      content,
    };
  }

  /**
   * Extract unique locators from page actions
   */
  private extractLocators(page: DetectedPage): LocatorEntry[] {
    const locatorMap = new Map<string, LocatorEntry>();
    
    for (const action of page.actions) {
      if (!action.element) continue;
      
      // Skip navigate actions (no element interaction)
      if (action.type === 'navigate') continue;
      
      const locator = this.locatorBuilder.build(action.element);
      const name = this.locatorBuilder.generateLocatorName(action.element, action.type);
      
      // Use locator string as key to deduplicate
      const key = locator.locator;
      if (!locatorMap.has(key)) {
        locatorMap.set(key, {
          name: this.ensureUniqueName(name, locatorMap),
          locator,
          actionType: action.type,
        });
      }
    }
    
    return Array.from(locatorMap.values());
  }

  /**
   * Ensure locator name is unique
   */
  private ensureUniqueName(name: string, existing: Map<string, LocatorEntry>): string {
    const existingNames = new Set(Array.from(existing.values()).map(e => e.name));
    
    if (!existingNames.has(name)) {
      return name;
    }
    
    let counter = 2;
    while (existingNames.has(`${name}${counter}`)) {
      counter++;
    }
    
    return `${name}${counter}`;
  }

  /**
   * Generate page methods from actions
   */
  private generateMethods(page: DetectedPage, locators: LocatorEntry[]): PageMethod[] {
    const methods: PageMethod[] = [];
    const methodNames = new Set<string>();
    
    // Create a map from locator string to locator entry
    const locatorMap = new Map<string, LocatorEntry>();
    for (const l of locators) {
      locatorMap.set(l.locator.locator, l);
    }
    
    for (const action of page.actions) {
      if (!action.element || action.type === 'navigate') continue;
      
      const locator = this.locatorBuilder.build(action.element);
      const locatorEntry = locatorMap.get(locator.locator);
      if (!locatorEntry) continue;
      
      const method = this.actionToMethod(action, locatorEntry, methodNames);
      if (method) {
        methods.push(method);
        methodNames.add(method.name);
      }
    }
    
    return methods;
  }

  /**
   * Convert action to page method
   */
  private actionToMethod(
    action: RecordedAction, 
    locator: LocatorEntry,
    existingNames: Set<string>
  ): PageMethod | null {
    const locatorName = locator.name;
    let methodName = '';
    let implementation = '';
    let params: { name: string; type: string }[] = [];
    let comment = '';

    switch (action.type) {
      case 'click':
        methodName = `click${this.capitalize(locatorName)}`;
        implementation = `await this.getLocator('${locatorName}').click();`;
        comment = `Click on ${locator.locator.comment}`;
        break;

      case 'dblclick':
        methodName = `doubleClick${this.capitalize(locatorName)}`;
        implementation = `await this.getLocator('${locatorName}').dblclick();`;
        comment = `Double click on ${locator.locator.comment}`;
        break;

      case 'type':
        methodName = `fill${this.capitalize(locatorName)}`;
        params = [{ name: 'value', type: 'string' }];
        implementation = `await this.getLocator('${locatorName}').fill(value);`;
        comment = `Fill ${locator.locator.comment}`;
        break;

      case 'hover':
        methodName = `hoverOver${this.capitalize(locatorName)}`;
        implementation = `await this.getLocator('${locatorName}').hover();`;
        comment = `Hover over ${locator.locator.comment}`;
        break;

      case 'rightclick':
        methodName = `rightClick${this.capitalize(locatorName)}`;
        implementation = `await this.getLocator('${locatorName}').click({ button: 'right' });`;
        comment = `Right click on ${locator.locator.comment}`;
        break;

      case 'select':
        methodName = `select${this.capitalize(locatorName)}`;
        params = [{ name: 'value', type: 'string' }];
        implementation = `await this.getLocator('${locatorName}').selectOption(value);`;
        comment = `Select option in ${locator.locator.comment}`;
        break;

      case 'scroll':
        // Skip scroll - not typically useful in page objects
        return null;

      case 'keypress':
        methodName = `pressKey${this.capitalize(locatorName)}`;
        params = [{ name: 'key', type: 'string' }];
        implementation = `await this.getLocator('${locatorName}').press(key);`;
        comment = `Press key on ${locator.locator.comment}`;
        break;

      default:
        return null;
    }

    // Ensure unique method name
    if (existingNames.has(methodName)) {
      return null; // Skip duplicate methods
    }

    return {
      name: methodName,
      locatorName,
      actionType: action.type,
      comment,
      params,
      implementation,
    };
  }

  /**
   * Format a method for code output
   */
  private formatMethod(method: PageMethod): string {
    const paramsStr = method.params?.map(p => `${p.name}: ${p.type}`).join(', ') || '';
    
    return `  /**
   * ${method.comment}
   */
  async ${method.name}(${paramsStr}): Promise<void> {
    ${method.implementation}
  }`;
  }

  /**
   * Generate test cases from pages
   */
  private generateTestCases(pages: DetectedPage[]): string {
    if (pages.length === 0) {
      return '  test(\'empty test\', async ({ page }) => {\n    // No actions recorded\n  });';
    }

    // Group actions into test steps
    const steps: string[] = [];
    
    // Initialize page objects
    const pageInits = pages.map(p => 
      `    const ${this.uncapitalize(p.className)} = new ${p.className}(page);`
    ).join('\n');

    // Generate action calls
    for (const detectedPage of pages) {
      const pageVar = this.uncapitalize(detectedPage.className);
      
      // Add navigation
      steps.push(`\n    // Navigate to ${detectedPage.title}`);
      steps.push(`    await ${pageVar}.navigate();`);
      
      // Add actions
      for (const action of detectedPage.actions) {
        if (action.type === 'navigate' || !action.element) continue;
        
        const locator = this.locatorBuilder.build(action.element);
        const locatorName = this.locatorBuilder.generateLocatorName(action.element, action.type);
        const methodName = this.getMethodName(action.type, locatorName);
        
        if (methodName) {
          let call = `await ${pageVar}.${methodName}(`;
          
          // Add parameters based on action type
          if (action.type === 'type' && action.data?.value) {
            call += `'${this.escapeString(action.data.value)}'`;
          } else if (action.type === 'keypress' && action.data?.key) {
            call += `'${action.data.key}'`;
          } else if (action.type === 'select' && action.data?.value) {
            call += `'${this.escapeString(action.data.value)}'`;
          }
          
          call += ');';
          steps.push(`    ${call}`);
        }
      }
    }

    return `  test('User flow test', async ({ page }) => {
${pageInits}
${steps.join('\n')}
  });`;
  }

  /**
   * Get method name for an action type
   */
  private getMethodName(actionType: string, locatorName: string): string | null {
    const cap = this.capitalize(locatorName);
    
    switch (actionType) {
      case 'click': return `click${cap}`;
      case 'dblclick': return `doubleClick${cap}`;
      case 'type': return `fill${cap}`;
      case 'hover': return `hoverOver${cap}`;
      case 'rightclick': return `rightClick${cap}`;
      case 'select': return `select${cap}`;
      case 'keypress': return `pressKey${cap}`;
      default: return null;
    }
  }

  private capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  private uncapitalize(str: string): string {
    return str.charAt(0).toLowerCase() + str.slice(1);
  }

  private escapeString(str: string): string {
    return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
  }

  private toFileName(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
  }
}

